name: Deploy Website to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout the GitHub repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Copy website files to EC2 user's home directory
      - name: Copy Website to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          source: "index.html,style.css,script.js"
          target: "/home/ec2-user/website"

      # 3. Move files into Nginx directory using sudo
      - name: Deploy Files to Nginx
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            sudo mkdir -p /var/www/html
            sudo cp -r /home/ec2-user/website/* /var/www/html/
            sudo chmod -R 755 /var/www/html

      # 4. Restart Nginx
      - name: Restart Nginx
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            sudo systemctl restart nginx
            sudo systemctl status nginx --no-pager